#
# PROGRAM: Lab Training Exercise
# Author: Leang Y Chheav
#

CXX = g++
CXXFLAGS = -Wall -Werror -ansi -pedantic -std=c++14

labtrain: labtrain.o
	$(CXX) $(CXXFLAGS) -o labtrain labtrain.o

labtrain.o: labtrain.cpp

clean:
	rm -f *.o labtrain
